### ISSUE TITLE
De ce ReportGenerator extinde Classroom?

### ISSUE THREAD

**Issue by benn876** [raduandreipopescu/course10-hoomework#1]
Nu ii corect ca ReportGenerator sa extinda Classroom. Pentru ca vine urmatoarea intrebare: Ii ReportGenerator un Classroom? Si raspunsu ii ca nu. Poti sa faci functii statice in Classroom daca vrei sa fie apelate din alte clase fara a instantia un obiect.

**Comment by raduandreipopescu** [comment]
Am facut modificarile necesare.
ReportGenerator nu mai extinde Classroom si doar apeleaza metodele statice din Classroom.

Multumesc.
